credentials:
  usernames:
    pmaru:
      email: prithivimaruthachalam@gmail.com
      name: Prithivi Maruthachalam
      password: '123' # To be replaced with hashed password
    araja:
      email: akshayar0811@gmail.com
      name: Akshaya Rajasekaran
      password: '456' # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
  - prithivimaruthachalam@gmail.com
